FROM adoptopenjdk/openjdk16:jdk-16.0.2_7-ubuntu as Java16

FROM adoptopenjdk/openjdk15:jdk-15.0.2_7-ubuntu as Java15

FROM adoptopenjdk/openjdk14:jdk-14.0.2_12-ubuntu as Java14

FROM adoptopenjdk/openjdk13:jdk-13.0.2_8-ubuntu as Java13

FROM adoptopenjdk/openjdk12:jdk-12.0.2_10-ubuntu as Java12

FROM adoptopenjdk/openjdk11:jdk-11.0.18_10-ubuntu as Java11

FROM adoptopenjdk/openjdk8:jdk8u362-b09-ubuntu as Java8

FROM ubuntu:latest as APP
#RUN apt-get update && \
#    apt-get install -y openjdk-18-jdk && \
#    apt-get install -y ant && \
#    apt-get clean;
RUN apt-get update
RUN apt install -y wget
SHELL ["/bin/bash", "-c"]
#ENV JAVA_HOME /usr/lib/jvm/java-18-openjdk-amd64/
#RUN export JAVA_HOME
RUN wget https://github.com/github/codeql-action/releases/latest/download/codeql-bundle.tar.gz
RUN mkdir -p codeql-bundle
RUN mkdir -p react-app
RUN tar -xvzf codeql-bundle.tar.gz -C codeql-bundle
RUN rm codeql-bundle.tar.gz
ENV PATH="$PATH:/codeql-bundle/codeql"
COPY . ./react-app
COPY docker-run.sh .
COPY --from=Java16 /opt/java/openjdk /opt/java/openjdk16
COPY --from=Java15 /opt/java/openjdk /opt/java/openjdk15
COPY --from=Java14 /opt/java/openjdk /opt/java/openjdk14
COPY --from=Java13 /opt/java/openjdk /opt/java/openjdk13
COPY --from=Java12 /opt/java/openjdk /opt/java/openjdk12
COPY --from=Java11 /opt/java/openjdk /opt/java/openjdk11
COPY --from=Java8 /opt/java/openjdk /opt/java/openjdk8
ENV NODE_VERSION=16.13.0
RUN apt install dos2unix
RUN apt install -y curl
#RUN apt-get install unzip
#RUN apt-get install zip
#RUN curl -s "https://get.sdkman.io" | bash
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
#RUN source "$HOME/.sdkman/bin/sdkman-init.sh"
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
#RUN \
#    cd /usr/local && \
#    curl -L https://services.gradle.org/distributions/gradle-5.4-bin.zip -o gradle-5.4-bin.zip && \
#    unzip gradle-5.4-bin.zip && \
#    rm gradle-5.4-bin.zip;
# Export some environment variables
#ENV GRADLE_HOME=/usr/local/gradle-5.4
#ENV PATH=$PATH:$JAVA_HOME/bin